apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - pvc.yaml
  - download-job.yaml
  - llm-inference-service.yaml
  - model-ref.yaml
  - tenant.yaml
  - auth-policy.yaml
  - subscriptions.yaml
