apiVersion: maas.opendatahub.io/v1alpha1
kind: MaaSModelRef
metadata:
  name: gemma2-9b-fp8
  namespace: llm-inference
  labels:
    app.kubernetes.io/name: gemma2-9b-fp8
spec:
  modelRef:
    kind: LLMInferenceService
    name: gemma2-9b-fp8
