# ClusterSecretStore allows any namespace to pull secrets from Vault.
# Requires the vault-token Secret in vault-dev namespace.
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: "http://vault.vault-dev.svc:8200"
      path: "secret"
      version: "v2"
      auth:
        tokenSecretRef:
          name: vault-token
          key: token
          namespace: vault-dev
