apiVersion: v1
kind: Secret
metadata:
  name: vault-token
  namespace: vault-dev
type: Opaque
stringData:
  token: REPLACE_WITH_VAULT_TOKEN
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: vault-dev
spec:
  provider:
    vault:
      server: "http://vault.vault-dev.svc:8200"
      path: "secret"
      version: "v2"
      auth:
        tokenSecretRef:
          name: vault-token
          key: token
