apiVersion: operator.authorino.kuadrant.io/v1beta1
kind: Authorino
metadata:
  name: authorino
  namespace: kuadrant-system
spec:
  clusterWide: true
  supersedingHostSubsets: true
  listener:
    tls:
      enabled: true
      certSecretRef:
        name: authorino-tls
