apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  labels:
    app.kubernetes.io/instance: maas-demo-gateway
    app.kubernetes.io/part-of: multi-cluster-lb
  name: gemma-cluster3-tls
  namespace: models-as-a-service
spec:
  host: inference-b.sandbox2582.opentlc.com
  trafficPolicy:
    tls:
      insecureSkipVerify: true
      mode: SIMPLE
