apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: gemma-cluster-a-tls
  namespace: models-as-a-service
  labels:
    app.kubernetes.io/part-of: multi-cluster-lb
spec:
  host: gemma2-9b-fp8-direct-llm-inference.apps.cluster-4l6x6.4l6x6.sandbox1213.opentlc.com
  trafficPolicy:
    connectionPool:
      http:
        h2UpgradePolicy: DO_NOT_UPGRADE
    tls:
      mode: SIMPLE
      insecureSkipVerify: true
      sni: gemma2-9b-fp8-direct-llm-inference.apps.cluster-4l6x6.4l6x6.sandbox1213.opentlc.com
