apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: gemma-cluster-a-tls
  namespace: openshift-ingress
  labels:
    app.kubernetes.io/part-of: multi-cluster-lb
spec:
  host: gemma2-9b-fp8-inference-llm-inference.apps.cluster-4l6x6.4l6x6.sandbox1213.opentlc.com
  trafficPolicy:
    tls:
      mode: SIMPLE
      insecureSkipVerify: true
