apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: maas-demo-gateway
    app.kubernetes.io/part-of: multi-cluster-lb
  name: gemma2-9b-fp8-cluster3
  namespace: models-as-a-service
spec:
  externalName: gemma2-9b-fp8-direct-models-as-a-service.apps.cluster-bf44z.bf44z.sandbox2582.opentlc.com
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 443
  sessionAffinity: None
  type: ExternalName
