apiVersion: v1
kind: Service
metadata:
  name: gemma2-9b-fp8-cluster-a
  namespace: models-as-a-service
  labels:
    app.kubernetes.io/part-of: multi-cluster-lb
spec:
  type: ExternalName
  externalName: aed794ce602fc4585aff1f0ab80130b1-1131672273.us-east-2.elb.amazonaws.com
  ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: 443
