apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - service-entry.yaml
  - destination-rule.yaml
  - external-service.yaml
  - service-entry-gateway-ns.yaml
  - destination-rule-gateway-ns.yaml
  - httproute.yaml
  - authpolicy.yaml
  - token-rate-limit-policy.yaml
