apiVersion: networking.istio.io/v1
kind: ServiceEntry
metadata:
  name: gemma-cluster-a-vllm
  namespace: models-as-a-service
  labels:
    app.kubernetes.io/part-of: multi-cluster-lb
spec:
  hosts:
    - aed794ce602fc4585aff1f0ab80130b1-1131672273.us-east-2.elb.amazonaws.com
  location: MESH_EXTERNAL
  ports:
    - name: https
      number: 443
      protocol: HTTPS
  resolution: DNS
