apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - authorino-servicemonitor.yaml
  - limitador-servicemonitor.yaml
  - kserve-servicemonitor.yaml
  - dashboard-configmap.yaml
  - prometheus-rules.yaml
  - monitoringstack-patch.yaml
