apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../profiles/multi-cluster/gateway-cluster
patches:
  # ServiceEntry — remote inference cluster hosts
  - target:
      kind: ServiceEntry
      name: remote-inference-cluster
    patch: |-
      - op: replace
        path: /spec/hosts/0
        value: qwen25-7b-inference-llm-inference.apps.cluster-4l6x6.4l6x6.sandbox1213.opentlc.com
  # Service (ExternalName) — externalName
  - target:
      kind: Service
      name: inference-backend
    patch: |-
      - op: replace
        path: /spec/externalName
        value: qwen25-7b-inference-llm-inference.apps.cluster-4l6x6.4l6x6.sandbox1213.opentlc.com
  # DestinationRule — host
  - target:
      kind: DestinationRule
      name: remote-inference-tls
    patch: |-
      - op: replace
        path: /spec/host
        value: qwen25-7b-inference-llm-inference.apps.cluster-4l6x6.4l6x6.sandbox1213.opentlc.com
  # HTTPRoute — Host header rewrite
  - target:
      kind: HTTPRoute
      name: multi-cluster-inference
    patch: |-
      - op: replace
        path: /spec/rules/0/filters/0/requestHeaderModifier/set/0/value
        value: qwen25-7b-inference-llm-inference.apps.cluster-4l6x6.4l6x6.sandbox1213.opentlc.com
  # AuthPolicy — Keycloak issuer URL
  - target:
      kind: AuthPolicy
      name: ai-gateway-oidc-auth
    patch: |-
      - op: replace
        path: /spec/rules/authentication/keycloak-jwt/jwt/issuerUrl
        value: https://keycloak-keycloak.apps.cluster-6crhb.6crhb.sandbox1011.opentlc.com/realms/ai-bridge
  # Multi-cluster LB — Cluster 3 vLLM endpoint
  - target:
      kind: ServiceEntry
      name: gemma-cluster3-vllm
    patch: |-
      - op: replace
        path: /spec/hosts/0
        value: a41cf615615014b66bf7d3ccbace4de3-926113304.us-east-2.elb.amazonaws.com
  - target:
      kind: DestinationRule
      name: gemma-cluster3-tls
    patch: |-
      - op: replace
        path: /spec/host
        value: a41cf615615014b66bf7d3ccbace4de3-926113304.us-east-2.elb.amazonaws.com
  - target:
      kind: Service
      name: gemma2-9b-fp8-cluster3
    patch: |-
      - op: replace
        path: /spec/externalName
        value: a41cf615615014b66bf7d3ccbace4de3-926113304.us-east-2.elb.amazonaws.com
