apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - subscription.yaml
  - uiplugin.yaml
  - perses-instance.yaml
  - perses-datasource.yaml
  - perses-dashboard.yaml
