apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-science-perses
  namespace: redhat-ods-monitoring
  labels:
    app: data-science-perses
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-science-perses
  template:
    metadata:
      labels:
        app: data-science-perses
    spec:
      serviceAccountName: data-science-perses
      containers:
        - name: perses
          image: registry.redhat.io/cluster-observability-operator/perses-rhel9@sha256:19b297eac0249f7375b5df7b936a7e17055e5dd1c17cccd0229b096482687c36
          args:
            - "--config=/etc/perses/config/config.yaml"
            - "--web.route-prefix=/perses/api"
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /etc/perses/config
            - name: db
              mountPath: /tmp/local_db
          livenessProbe:
            httpGet:
              path: /perses/api/api/v1/health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /perses/api/api/v1/health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              memory: 256Mi
      volumes:
        - name: config
          configMap:
            name: data-science-perses-config
        - name: db
          emptyDir: {}
